pipeline{
    agent any 

    environment {
        DOCKER_IMAGE = 'calendario-api'
        CONTAINER_NAME = 'dockercalendario'
        DOCKER_NETWORK = 'dockerfestivos_red'
        DOCKER_BUILD_DIR = 'presentacion'
        HOST_PORT = '9085'
        CONTAINER_PORT = '8080'
        
    }
    
    stages{
        stage('Generar ejecutable MAven'){
            steps{
                bat 'mvn clean package -DskipTests'           
              
            }
        }
    stage('construir la imagen'){
        steps{
            dir(DOCKER_BUILD_DIR) {
                bat "docker build -t ${DOCKER_IMAGE} ."
                
                }
            }

        }

    }
    stage('Limpiar contenedor existente'){
        steps{
            script{
                catchError(buildResult: 'SUCCESS', stageResult: 'UNSTABLE') {
                    bat """
                    docker container inspect ${CONTAINER_NAME} > nul 2>&1 && ( 
                    docker container stop ${CONTAINER_NAME}
                    docker container rm ${CONTAINER_NAME}
                    )|| ECHO "No existe el contenedor '${CONTAINER_NAME}'."
                    """
                }
            }

        }

    }
       stage('Desplegar el contenedor'){
        steps{
            script{
                bat "docker container run --network ${DOCKER_NETWORK} --name ${CONTAINER_NAME} -p ${HOST_PORT}:${CONTAINER_PORT} -d ${DOCKER_IMAGE}"    
            }

        }

    }

    }
    
}